/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cosmoadornos.cosmopos.view;

import com.cosmoadornos.cosmopos.controller.ClienteController;
import com.cosmoadornos.cosmopos.dao.TipoDocumentoDAO;
import com.cosmoadornos.cosmopos.model.Cliente;
import com.cosmoadornos.cosmopos.model.TipoDocumento;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author b41n
 */
public class ClienteAgregar extends javax.swing.JFrame {
    
    TipoDocumentoDAO dao = new TipoDocumentoDAO();
    ArrayList<TipoDocumento> lista;
    int documentoId;
    

    /**
     * Creates new form Cliente
     */
    public ClienteAgregar() {
        lista = dao.obtenerTiposDocumentos();
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Agregar nuevo cliente");
        llenarListaDocumentos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtDocumento = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtDocumento1 = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        cmbTipoDocumento = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbTipoPersona = new javax.swing.JComboBox<>();
        jSeparator7 = new javax.swing.JSeparator();
        cmbTipoPersona1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmbTipoPersona2 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cmbTipoPersona3 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cmbTipoPersona4 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        cmbResponsabilidades = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        txtTelefono1 = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(null);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDocumento.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        txtDocumento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDocumento.setBorder(null);
        jPanel1.add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 160, -1));

        txtNombres.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        txtNombres.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombres.setBorder(null);
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 680, -1));

        txtApellidos.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        txtApellidos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtApellidos.setBorder(null);
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 560, 219, -1));

        txtTelefono.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        txtTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTelefono.setBorder(null);
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 219, -1));

        txtEmail.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmail.setBorder(null);
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 450, -1));

        txtDireccion.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        txtDireccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDireccion.setBorder(null);
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 680, -1));

        txtDocumento1.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        txtDocumento1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDocumento1.setBorder(null);
        jPanel1.add(txtDocumento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 70, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, 219, 42));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, 219, 42));

        cmbTipoDocumento.setBackground(new java.awt.Color(153, 153, 153));
        cmbTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        cmbTipoDocumento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoDocumentoItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbTipoDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 160, 210, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 160, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 680, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 219, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 580, 219, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 680, 10));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 450, 10));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(57, 113, 177));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Apellidos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, 219, -1));

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(57, 113, 177));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nombre Empresa");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 680, -1));

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(57, 113, 177));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Documento");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 160, -1));

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(57, 113, 177));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("E-mail");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 440, -1));

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(57, 113, 177));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Teléfono");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 219, -1));

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(57, 113, 177));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Dirección");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 680, -1));

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(57, 113, 177));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Tipo de documento");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 210, -1));

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("X");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 20, -1));

        jLabel9.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(57, 113, 177));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Tipo Persona");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 210, -1));

        jLabel10.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(57, 113, 177));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("DV");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 70, -1));

        cmbTipoPersona.setBackground(new java.awt.Color(153, 153, 153));
        cmbTipoPersona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        cmbTipoPersona.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoPersonaItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbTipoPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 210, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 70, 10));

        cmbTipoPersona1.setBackground(new java.awt.Color(153, 153, 153));
        cmbTipoPersona1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        cmbTipoPersona1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoPersona1ItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbTipoPersona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 210, -1));

        jLabel11.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(57, 113, 177));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Departamento");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 210, -1));

        jLabel12.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(57, 113, 177));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Municipio");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 240, -1));

        cmbTipoPersona2.setBackground(new java.awt.Color(153, 153, 153));
        cmbTipoPersona2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        cmbTipoPersona2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoPersona2ItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbTipoPersona2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 240, -1));

        jLabel13.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(57, 113, 177));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Código Postal");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 210, -1));

        cmbTipoPersona3.setBackground(new java.awt.Color(153, 153, 153));
        cmbTipoPersona3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        cmbTipoPersona3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoPersona3ItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbTipoPersona3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 210, -1));

        jLabel14.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(57, 113, 177));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Régimen");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 210, -1));

        cmbTipoPersona4.setBackground(new java.awt.Color(153, 153, 153));
        cmbTipoPersona4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        cmbTipoPersona4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoPersona4ItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbTipoPersona4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 210, -1));

        jLabel15.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(57, 113, 177));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Responsabilidades");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 210, -1));

        cmbResponsabilidades.setBackground(new java.awt.Color(153, 153, 153));
        cmbResponsabilidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        cmbResponsabilidades.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbResponsabilidadesItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbResponsabilidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 240, -1));

        jLabel16.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(57, 113, 177));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Lista");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 219, -1));

        txtTelefono1.setEditable(false);
        txtTelefono1.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        txtTelefono1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTelefono1.setBorder(null);
        txtTelefono1.setFocusable(false);
        jPanel1.add(txtTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 219, -1));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 219, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void llenarListaDocumentos(){
        for(int i = 0 ; i <= lista.size()-1; i++){
            cmbTipoDocumento.addItem(lista.get(i).getTipoDocumento());
        }
    }
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        //this.hide();
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        Cliente cliente = new Cliente();
        
        cliente.setTipoDocumentoId(documentoId);
        cliente.setDocumento(txtDocumento.getText());
        cliente.setNombres(txtNombres.getText());
        cliente.setApellidos(txtApellidos.getText());
        cliente.setTelefono(txtTelefono.getText());
        cliente.setDireccion(txtDireccion.getText());
        cliente.setEmail(txtEmail.getText());
        
        ClienteController clicon = new ClienteController();
        
        if(clicon.guardarCliente(cliente)){
            JOptionPane.showMessageDialog(null,"Cliente guardado en la base de datos.");
            //VentasDark.txtDocumento.setText(cliente.getDocumento());
            //VentasDark.txtNombre.setText(cliente.getNombres()+" "+cliente.getApellidos());
            //cliente = clicon.buscarCliente(cliente.getDocumento());
            //VentasDark.cliente = cliente;
            dispose();
        }else{
            JOptionPane.showMessageDialog(null,"Error guardando el cliente.");
            System.out.println("Error guardando el cliente.");
        }
        
        
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cmbTipoDocumentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoDocumentoItemStateChanged
        // TODO add your handling code here:
        
        String tipoDocumento = cmbTipoDocumento.getSelectedItem().toString();
        for(int i = 0 ; i <= lista.size()-1 ; i++){
            if(!tipoDocumento.equals("AA")){
                if(lista.get(i).getTipoDocumento().contains(tipoDocumento)){
                    System.out.println("Tipo de documento: "
                            + ""+lista.get(i).getDescripcion());
                    documentoId = lista.get(i).getTipoDocumentoId();
                    btnGuardar.setEnabled(true);
                }
            }
        }
    }//GEN-LAST:event_cmbTipoDocumentoItemStateChanged

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void cmbTipoPersonaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoPersonaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoPersonaItemStateChanged

    private void cmbTipoPersona1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoPersona1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoPersona1ItemStateChanged

    private void cmbTipoPersona2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoPersona2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoPersona2ItemStateChanged

    private void cmbTipoPersona3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoPersona3ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoPersona3ItemStateChanged

    private void cmbTipoPersona4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoPersona4ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoPersona4ItemStateChanged

    private void cmbResponsabilidadesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbResponsabilidadesItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbResponsabilidadesItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }else if("Darcula".equals(info.getName())){
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteAgregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbResponsabilidades;
    private javax.swing.JComboBox<String> cmbTipoDocumento;
    private javax.swing.JComboBox<String> cmbTipoPersona;
    private javax.swing.JComboBox<String> cmbTipoPersona1;
    private javax.swing.JComboBox<String> cmbTipoPersona2;
    private javax.swing.JComboBox<String> cmbTipoPersona3;
    private javax.swing.JComboBox<String> cmbTipoPersona4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtDireccion;
    public static javax.swing.JTextField txtDocumento;
    public static javax.swing.JTextField txtDocumento1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefono1;
    // End of variables declaration//GEN-END:variables
}
