/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cosmoadornos.cosmopos.view;

import com.cosmoadornos.cosmopos.controller.EmpresaController;
import com.cosmoadornos.cosmopos.dao.TipoDocumentoDAO;
import com.cosmoadornos.cosmopos.model.Empresa;
import com.cosmoadornos.cosmopos.model.Factura;
import com.cosmoadornos.cosmopos.model.TipoDocumento;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author b41n
 */
public class FacturaElectronica extends javax.swing.JFrame {
    Factura factura;
    TipoDocumentoDAO dao = new TipoDocumentoDAO();
    ArrayList<TipoDocumento> lista;
    int documentoId;
    
    EmpresaController empcon = new EmpresaController();
    
    Empresa empresa;
    
    Empresa empresaCliente;

    /**
     * Creates new form Cliente
     */
    public FacturaElectronica() {
        lista = dao.obtenerTiposDocumentos();
        initComponents();
        this.setLocationRelativeTo(null);
        //this.setTitle("Agregar nuevo cliente");
        btnSiguiente1.setEnabled(false);
        //();
    }

    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    
    private void verFactura(){
        //private JWebBrowser fileBrowser 
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCards = new javax.swing.JPanel();
        pnlCliente = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        txtNIT = new javax.swing.JTextField();
        txtResponsabilidades = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSiguiente1 = new javax.swing.JButton();
        btnBuscarCliente = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        txtClienteNit = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        txtRegimen = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pnlProductos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pnlValidacion = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        pnlCards.setLayout(new java.awt.CardLayout());

        pnlCliente.setBackground(new java.awt.Color(255, 255, 255));
        pnlCliente.setBorder(null);
        pnlCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(57, 113, 177));
        jLabel8.setText("X");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        pnlCliente.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 20, -1));

        txtEmpresa.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        txtEmpresa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmpresa.setBorder(null);
        txtEmpresa.setEnabled(false);
        txtEmpresa.setFocusable(false);
        pnlCliente.add(txtEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 490, -1));

        txtNIT.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        txtNIT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNIT.setBorder(null);
        txtNIT.setEnabled(false);
        txtNIT.setFocusable(false);
        pnlCliente.add(txtNIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 219, -1));

        txtResponsabilidades.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        txtResponsabilidades.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtResponsabilidades.setBorder(null);
        txtResponsabilidades.setEnabled(false);
        txtResponsabilidades.setFocusable(false);
        pnlCliente.add(txtResponsabilidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 219, -1));

        txtTelefono.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        txtTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTelefono.setBorder(null);
        txtTelefono.setEnabled(false);
        txtTelefono.setFocusable(false);
        pnlCliente.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 219, -1));

        txtEmail.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmail.setBorder(null);
        txtEmail.setEnabled(false);
        txtEmail.setFocusable(false);
        pnlCliente.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 490, -1));

        txtDireccion.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        txtDireccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDireccion.setBorder(null);
        txtDireccion.setEnabled(false);
        txtDireccion.setFocusable(false);
        pnlCliente.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 490, -1));
        pnlCliente.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 480, 10));
        pnlCliente.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 490, 10));
        pnlCliente.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 219, 10));
        pnlCliente.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 219, 10));
        pnlCliente.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 219, 10));
        pnlCliente.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 490, 10));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(57, 113, 177));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Responsabilidades");
        pnlCliente.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 219, -1));

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(57, 113, 177));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nit");
        pnlCliente.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 219, -1));

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(57, 113, 177));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NOMBRE DE LA EMPRESA");
        pnlCliente.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 110, 490, -1));

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(57, 113, 177));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("E-mail");
        pnlCliente.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 219, -1));

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(57, 113, 177));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Teléfono");
        pnlCliente.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 219, -1));

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(57, 113, 177));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Dirección");
        pnlCliente.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 219, -1));

        btnSiguiente1.setText("SIGUIENTE");
        btnSiguiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguiente1ActionPerformed(evt);
            }
        });
        pnlCliente.add(btnSiguiente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 610, 220, 42));

        btnBuscarCliente.setText("BUSCAR");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });
        pnlCliente.add(btnBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 220, 42));
        pnlCliente.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 219, 10));

        txtClienteNit.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        txtClienteNit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtClienteNit.setText("123456789");
        txtClienteNit.setBorder(null);
        pnlCliente.add(txtClienteNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 219, -1));
        pnlCliente.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 490, 10));

        txtRegimen.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        txtRegimen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRegimen.setBorder(null);
        txtRegimen.setEnabled(false);
        txtRegimen.setFocusable(false);
        pnlCliente.add(txtRegimen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 490, -1));

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(57, 113, 177));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("REGIMEN");
        pnlCliente.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 219, -1));

        pnlCards.add(pnlCliente, "card2");

        pnlProductos.setBackground(new java.awt.Color(255, 255, 255));
        pnlProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "PRODUCTO", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        pnlProductos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 484, 390));

        jButton1.setText("SIGUIENTE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnlProductos.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 610, 220, 43));

        jButton2.setText("VOLVER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        pnlProductos.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 210, 43));

        pnlCards.add(pnlProductos, "card3");

        pnlValidacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setText("ENVIAR CORREO");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        pnlValidacion.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 230, 43));

        jButton5.setText("TERMINAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        pnlValidacion.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 610, 220, 43));

        jButton3.setText("VOLVER");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        pnlValidacion.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 220, 43));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jScrollPane2.setViewportView(jTextArea1);

        pnlValidacion.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 490, 100));

        pnlCards.add(pnlValidacion, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void llenarListaDocumentos(){
        for(int i = 0 ; i <= lista.size()-1; i++){
            //cmbTipoDocumento.addItem(lista.get(i).getTipoDocumento());
        }
    }
    
    private void btnSiguiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguiente1ActionPerformed
        // TODO add your handling code here:
        //this.hide();
        pnlCliente.setVisible(false);
        pnlProductos.setVisible(true);
        //dispose();
    }//GEN-LAST:event_btnSiguiente1ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:
        empresaCliente =null;
        String nit;
        nit = String.valueOf(txtClienteNit.getText());
        buscarDatosEmpresa(nit);
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void buscarDatosEmpresa(String nit){
        empresaCliente = empcon.buscarDatosEmpresa(nit);
        
        if(empresaCliente.getCompanyNIT().equals(nit)){
            mostrarDatosEmpresa(empresaCliente);
            btnSiguiente1.setEnabled(true);
        }else{
            //JOptionPane.showMessageDialog(this, "No encontrado.");
            limpiarDatosEmpresa();
            int opt = JOptionPane.showConfirmDialog(this, "Cliente no encontrado\n"+"Desea agregar un nuevo cliente?");
            
            if(opt==1){
                //JOptionPane.showMessageDialog(null, "No agregar cliente.");
            }
            if(opt==JOptionPane.OK_OPTION){
                //JOptionPane.showMessageDialog(null,"Agregar un nuevo cliente");
                guardarCliente(nit);
            }
        }
    }
    
    private void guardarCliente(String nit){
        ClienteAgregar nuevoCliente = new ClienteAgregar();
        nuevoCliente.setVisible(true);
        ClienteAgregar.txtDocumento.setText(nit);
        
    }
    
    private void mostrarDatosEmpresa(Empresa empresa){
        txtEmpresa.setText(empresa.getCompanyName());
        txtNIT.setText(empresa.getCompanyNIT());
        txtRegimen.setText(empresa.getRegimen().getRegimenNombre());
        txtEmail.setText(empresa.getEmail());
        txtTelefono.setText(empresa.getTelefono());
        txtDireccion.setText(empresa.getDireccion());
        txtResponsabilidades.setText(empresa.getRegimen().getRegimenNombre());
    }
    private void limpiarDatosEmpresa(){
        txtEmpresa.setText("");
        txtNIT.setText("");
        txtRegimen.setText("");
        txtEmail.setText("");
        txtTelefono.setText("");
        txtDireccion.setText("");
        txtResponsabilidades.setText("");
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        pnlProductos.setVisible(false);
        pnlValidacion.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        pnlProductos.setVisible(false);
        pnlCliente.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        pnlValidacion.setVisible(false);
        pnlProductos.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }else if("Darcula".equals(info.getName())){
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacturaElectronica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnSiguiente1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel pnlCards;
    private javax.swing.JPanel pnlCliente;
    private javax.swing.JPanel pnlProductos;
    private javax.swing.JPanel pnlValidacion;
    public static javax.swing.JTextField txtClienteNit;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    public static javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtNIT;
    public static javax.swing.JTextField txtRegimen;
    private javax.swing.JTextField txtResponsabilidades;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
