/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cosmoadornos.cosmopos.view;

import com.cosmoadornos.cosmopos.controller.LoginController;
import com.cosmoadornos.cosmopos.model.Permiso;
import com.cosmoadornos.cosmopos.model.Usuario;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Brayan Novoa <bnovoa.linux@gmail.com at cosmoadornos.com>
 */
public class Login extends javax.swing.JFrame {
    Usuario usuario;
    LoginController login = new LoginController();
    ArrayList<Permiso> permisos = new ArrayList();
    
    int xx;
    int xy;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        pnlHide.setBackground(new Color(0,0,0,200));
        //pnlHide.setVisible(false);
        //txtUsuario.setText("Brayan");
        //txtPasswd.setText("Novoa");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogin = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        txtPasswd = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtExit = new javax.swing.JTextField();
        txtUsuario2 = new javax.swing.JTextField();
        button1 = new java.awt.Button();
        txtUsuario3 = new javax.swing.JTextField();
        pnlHide = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLogin.setBackground(new java.awt.Color(33, 33, 35));
        pnlLogin.setBorder(null);
        pnlLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsuario.setBackground(new java.awt.Color(33, 33, 35));
        txtUsuario.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setText("Brayan");
        txtUsuario.setBorder(null);
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseClicked(evt);
            }
        });
        pnlLogin.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 139, -1));

        txtPasswd.setBackground(new java.awt.Color(33, 33, 35));
        txtPasswd.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        txtPasswd.setForeground(new java.awt.Color(255, 255, 255));
        txtPasswd.setText("Brayan");
        txtPasswd.setBorder(null);
        txtPasswd.setEchoChar('\u2022');
        txtPasswd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswdMouseClicked(evt);
            }
        });
        pnlLogin.add(txtPasswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 140, -1));
        pnlLogin.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 140, 10));
        pnlLogin.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 139, 10));

        txtExit.setEditable(false);
        txtExit.setBackground(new java.awt.Color(33, 33, 35));
        txtExit.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        txtExit.setForeground(new java.awt.Color(117, 117, 117));
        txtExit.setText("X");
        txtExit.setBorder(null);
        txtExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtExitMouseClicked(evt);
            }
        });
        pnlLogin.add(txtExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 20, -1));

        txtUsuario2.setEditable(false);
        txtUsuario2.setBackground(new java.awt.Color(33, 33, 35));
        txtUsuario2.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        txtUsuario2.setForeground(new java.awt.Color(57, 113, 177));
        txtUsuario2.setText("Contraseña");
        txtUsuario2.setBorder(null);
        txtUsuario2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsuario2MouseClicked(evt);
            }
        });
        pnlLogin.add(txtUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 139, -1));

        button1.setBackground(new java.awt.Color(255, 255, 255));
        button1.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        button1.setForeground(new java.awt.Color(33, 33, 35));
        button1.setLabel("Iniciar Sesión");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        pnlLogin.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 140, 41));

        txtUsuario3.setEditable(false);
        txtUsuario3.setBackground(new java.awt.Color(33, 33, 35));
        txtUsuario3.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        txtUsuario3.setForeground(new java.awt.Color(57, 113, 177));
        txtUsuario3.setText("Usuario");
        txtUsuario3.setBorder(null);
        txtUsuario3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsuario3MouseClicked(evt);
            }
        });
        pnlLogin.add(txtUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 139, -1));

        getContentPane().add(pnlLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 320, 410));

        pnlHide.setBackground(new java.awt.Color(0, 0, 0));
        pnlHide.setBorder(null);
        pnlHide.setMaximumSize(new java.awt.Dimension(320, 450));
        pnlHide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cosmoadornos/cosmopos/icons/CosmoPos.png"))); // NOI18N
        pnlHide.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 240, 80));

        jLabel3.setForeground(new java.awt.Color(117, 117, 117));
        jLabel3.setText("Desarrolloado por CosmoAdornos");
        pnlHide.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 220, -1));

        getContentPane().add(pnlHide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 410));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cosmoadornos/cosmopos/icons/intro.png"))); // NOI18N
        jLabel1.setBorder(null);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarSesion(){
        usuario = new Usuario(txtUsuario.getText(),txtPasswd.getText());
        String tipoUsuario = login.VerificarAcceso(usuario);
        //usuario.setUsuarioId(usuarioId);
        
        if(tipoUsuario!=null){
            Main main = new Main();
            
            main.usuario = usuario;
            usuario = null;
            //main.usuario = new Usuario(txtUsuario.getText(),txtPasswd.getText());
            permisos = login.obtenerPermisos(tipoUsuario);
            main.verificarPermisos(permisos);
            main.setVisible(true);
            this.dispose();
            //JOptionPane.showMessageDialog(null,"Bienvenido al sistema");
            
            
            
        }else{
            JOptionPane.showMessageDialog(null,"Verifique sus datos");
        }
    }
    
    private void txtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseClicked
        // TODO add your handling code here:
        txtUsuario.setText("");
    }//GEN-LAST:event_txtUsuarioMouseClicked

    private void txtPasswdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswdMouseClicked
        // TODO add your handling code here:
        txtPasswd.setText("");
    }//GEN-LAST:event_txtPasswdMouseClicked

    private void txtExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseClicked
        // TODO add your handling code here:
        //this.dispose();
        System.exit(0);
    }//GEN-LAST:event_txtExitMouseClicked

    private void txtUsuario2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuario2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuario2MouseClicked

    private void txtUsuario3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuario3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuario3MouseClicked

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        iniciarSesion();
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel pnlHide;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JTextField txtExit;
    private javax.swing.JPasswordField txtPasswd;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtUsuario2;
    private javax.swing.JTextField txtUsuario3;
    // End of variables declaration//GEN-END:variables
}
